### ISSUE TITLE
创建用户凭证不成功

### ISSUE THREAD

**Issue by charli2014** [Lafeng/deblocus#28]
在搭建服务时，在创建用户凭证这里一直不成功，提示如下：
```
panic: Unimplemented authsys for /etc/deblocus/user.conf

goroutine 1 [running]:
github.com/Lafeng/deblocus/tunnel.ThrowErr(0x7779a0, 0xc8200c51c0)
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/tunnel/common.go:106 +0x31
github.com/Lafeng/deblocus/tunnel.(*D5ServConf).validate(0xc820074100, 0x0, 0x0)
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/tunnel/config.go:148 +0x381
github.com/Lafeng/deblocus/tunnel.Parse_d5s_file(0x7c7710, 0xc, 0x1)
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/tunnel/config.go:324 +0xae
main.(*bootContext).cccHandler(0xc691a0, 0x0, 0x0)
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/bootContext.go:106 +0x27e
main.main()
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/deblocus.go:67 +0x4d0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
github.com/Lafeng/deblocus/golang/glog.(*loggingT).flushDaemon(0xc69520)
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/golang/glog/glog.go:900
created by github.com/Lafeng/deblocus/golang/glog.init.1
	/home/xtyd/golang/deblocus/src/github.com/Lafeng/deblocus/golang/glog/glog.go:411 +0x6f

goroutine 6 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by charli2014** [comment]
`/etc/deblocus/user.conf`文件如下
```
user01:test01
```
创建命令如下：
```
./deblocus -ccc [服务器ipv6地址]:9008 user01
```

**Comment by vickery** [comment]
把你的deblocus.d5s的前半部分贴出来（注意把重要信息遮掉）

**Comment by charli2014** [comment]
```
# -----------------------------
# deblocus server configuration
# -----------------------------

Auth               /etc/deblocus/user.conf
Cipher             AES256CFB
DenyDest           OFF
Listen             :9008
ServerName         SERVER_HK
Verbose            1
```

**Comment by vickery** [comment]
wiki中有这个选项的解释，格式：
`Auth     file:///etc/deblocus/user.conf`

**Comment by charli2014** [comment]
是我阅读不仔细了，没有注意到路径前面是有`file://`，非常感谢。
